name: Android Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  android-lint:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: dependencies
        run: npm install

      - name: lint
        run: |
          cd android
          ./gradlew ktlint
          cd ..

      - name: CheckStyle
        run: |
          cd android
          ./gradlew checkstyle
          cd ..

      - name: example-lint
        run: |
          cd example/android
          ./gradlew ktlint
          cd ../..

      - name: example-checkstyle
        run: |
          cd example/android
          ./gradlew checkstyle
          cd ../..
